#include "operations.h"
#include <stdio.h>
#include <stdlib.h>
    void initialize(void){}
    void addRemedio(void){}
    void showAll(void){}
    void showRemedioById(void){}
    void updateRemedio(void){}
    void removeRemedio(void){}